<?php

namespace CarsBundle\Repository;

/**
 * CarsCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarsCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
