<?php

namespace CarsBundle\Repository;

/**
 * CarsOptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarsOptionsRepository extends \Doctrine\ORM\EntityRepository
{
}
