<?php

namespace CarsBundle\Repository;

/**
 * CarsModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarsModelRepository extends \Doctrine\ORM\EntityRepository
{
}
