<?php

namespace CarsBundle\Repository;

/**
 * CarsBrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarsBrandRepository extends \Doctrine\ORM\EntityRepository
{
}
