<?php

namespace CarsBundle\Repository;

/**
 * OptionsTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionsTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
