stats:
    resource: "@StatsBundle/Resources/config/routing.yml"
    prefix:   /

customer:
    resource: "@CustomerBundle/Resources/config/routing.yml"
    prefix:   /

cars:
    resource: "@CarsBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
