cars_home:
    path:     /
    defaults: { _controller: CarsBundle:Cars:home }

cars_index:
    path:     /cars
    defaults: { _controller: CarsBundle:Cars:index }

cars_list:
    path:     /cars/cars
    defaults: { _controller: CarsBundle:Cars:all }

specifications_index:
    path:     /cars/specifications
    defaults: { _controller: CarsBundle:Specifications:index }

category_list:
    path:     /cars/specifications/categories
    defaults: { _controller: CarsBundle:Specifications:categoryList }

category_add:
    path:     /cars/specifications/category/add
    defaults: { _controller: CarsBundle:Specifications:addCategory }

category_update:
    path:     /cars/specifications/category/update/{id}
    defaults: { _controller: CarsBundle:Specifications:updateCategory }

category_delete:
    path:     /cars/specifications/category/delete/{id}
    defaults: { _controller: CarsBundle:Specifications:deleteCategory }

brand_list:
    path:     /cars/specifications/brand
    defaults: { _controller: CarsBundle:Specifications:brandList }

brand_add:
    path:     /cars/specifications/brand/add
    defaults: { _controller: CarsBundle:Specifications:addBrand }

brand_update:
    path:     /cars/specifications/brand/update/{id}
    defaults: { _controller: CarsBundle:Specifications:updateBrand }

brand_delete:
    path:     /cars/specifications/brand/delete/{id}
    defaults: { _controller: CarsBundle:Specifications:deleteBrand }

model_list:
    path:     /cars/specifications/model
    defaults: { _controller: CarsBundle:Specifications:modelList }

options_index:
    path:     /cars/options
    defaults: { _controller: CarsBundle:Options:index }