services:
    cars.carsBrand:
        class: CarsBundle\Manager\CarsBrandManager
        arguments: ["@doctrine"]
    cars.carsCategory:
        class: CarsBundle\Manager\CarsCategoryManager
        arguments: ["@doctrine"]
